#!/bin/bash

RUN_DIR=/var/vcap/sys/run/bosh-log-forwarder
LOG_DIR=/var/vcap/sys/log/bosh-log-forwarder
DATA_DIR=/var/vcap/store/bosh-log-forwarder
CONFIG_DIR=/var/vcap/jobs/bosh-log-forwarder/config

PIDFILE=$RUN_DIR/bosh-log-forwarder.pid
RUNAS=vcap

export PATH=/var/vcap/packages/filebeat:/var/vcap/jobs/bosh-log-forwarder/bin:$PATH

function pid_exists() {
  ps -p $1 &> /dev/null
}

case $1 in
  start)
    mkdir -p $RUN_DIR $LOG_DIR $DATA_DIR
    chown -R $RUNAS:$RUNAS $RUN_DIR $LOG_DIR $DATA_DIR

    generate_config.sh

    echo $$ > $PIDFILE

    exec chpst -u $RUNAS:$RUNAS \
      filebeat -c $CONFIG_DIR/filebeat.yml 
    ;;

  stop)
    PID=$(head -1 $PIDFILE)
    if [ ! -z $PID ] && pid_exists $PID; then
      kill $PID
    fi
    while [ -e /proc/$PID ]; do sleep 0.1; done
    rm -f $PIDFILE
    ;;

  *)
  echo "Usage: ctl {start|stop}" ;;
esac
exit 0
